# Generated by Django 2.1 on 2018-08-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_char', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_char', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_char', models.CharField(max_length=1)),
                ('full_char', models.CharField(max_length=100)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='prov_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Prov'),
        ),
    ]
