# Generated by Django 2.1 on 2018-08-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='town_id',
            new_name='town',
        ),
    ]
