# Generated by Django 2.1 on 2018-08-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20180817_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 8, 17, 13, 22, 43, 465599), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='date_n',
            field=models.CharField(default='', max_length=10, verbose_name='农历'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='date_p',
            field=models.DateField(auto_now=True, default=datetime.datetime(2018, 8, 17, 13, 22, 55, 546252), verbose_name='公历'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='week',
            field=models.CharField(default='', max_length=10, verbose_name='星期'),
        ),
    ]
